version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: '1'
      DB_HOST: db
      DB_NAME: fastapi
      DB_USER: fastapi
      DB_PASSWORD: fastapi
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fastapi
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: fastapi
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  db: